version: '3.4'

services:


  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: kafka
    container_name: kafka
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    command: >
        bash -c
        "(sleep 15s &&
        /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
        --create
        --zookeeper
        localhost:2181 --replication-factor 1 --partitions 1
        --topic dummy_topic &) && (supervisord -n)"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  cscservicereceive:
    image: ${DOCKER_REGISTRY-}cscservicereceive
    build:
      context: .
      dockerfile: CSCServiceReceive/Dockerfile

  movieapi:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: MovieAPI/Dockerfile


  voteandclassificationservice:
    image: ${DOCKER_REGISTRY-}voteandclassificationservice
    build:
      context: .
      dockerfile: VoteAndClassificationService/Dockerfile

   

