version: '3.4'

services:

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://192.168.0.22:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
        - SA_PASSWORD=Pass@word9
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"

  movieapi:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: MovieAPI/Dockerfile

  cscservicerequest:
    image: ${DOCKER_REGISTRY-}cscservicerequest
    build:
      context: .
      dockerfile: CSCServiceRequest/Dockerfile


  userapi:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: UserAPI/Dockerfile


  voteandclassificationservice:
    image: ${DOCKER_REGISTRY-}voteandclassificationservice
    build:
      context: .
      dockerfile: VoteAndClassificationService/Dockerfile


  cscconsumerserviceconsume:
    image: ${DOCKER_REGISTRY-}cscconsumerserviceconsume
    build:
      context: .
      dockerfile: CSCConsumerService/Dockerfile

